[General]
DisplayServer=wayland
InputMethod=
GreeterEnvironment=QT_QPA_PLATFORM=wayland,QT_QUICK_BACKEND=software,LIBGL_ALWAYS_SOFTWARE=1,QT_WAYLAND_SHELL_INTEGRATION=layer-shell

[Wayland]
CompositorCommand=kwin_wayland --no-lockscreen --no-global-shortcuts --inputmethod maliit-keyboard

[Theme]
Current=breeze
